management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
  servlet:
    threads:
      max: 1000
  tomcat:
    threads:
      max: 1000

spring:
  application:
    name: weibo-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000

Weibo:
  img:
    path: D:\Download

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql

mq:
  nameserver:
    addr: localhost:9876
  topicname: like
